### PR TITLE
LPS 158832

### PR DESCRIPTION
**Pull request by edalgrin**
IMPORTANT: this PR depends on https://github.com/liferay-frontend/liferay-portal/pull/2594

- LPS-158832 Replace remote-apps with client-extensions labels
- LPS-158832 Generate language files

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:frontend-remote-apps

**Comment by edalgrin** [comment]
Thanks @john-co for looking into this, just wanted to be say this PR depends on https://github.com/liferay-frontend/liferay-portal/pull/2594 but let me know if I can help/move it to the team repo!

**Comment by edalgrin** [comment]
If necessary I can split this one in 2 so we can already submit the part not dependant from https://github.com/liferay-frontend/liferay-portal/pull/2894

**Pull request closed without merging**
