### PR TITLE
LPS-110206 Staging view page does not show custom background CSS from…

### PR DESCRIPTION
**Pull request by moltam89**
… theme

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:stable

**Review by edalgrin — APPROVED** [review]
hi @moltam89, if this simple change fixes the issue we can forward this!

**Comment by moltam89** [comment]
Great, thanks @edalgrin!

**Comment by moltam89** [comment]
ci:forward

**Pull request closed without merging**
